koszyk = [
['kielecki','Majonez Kielecki 700ml','https://www.carrefour.pl/artykuly-spozywcze/sosy-oleje-ocet/majonez/majonez-kielecki-700-ml'],
['pizza','Dr. Oetker Guseppe Pizza z szynką i pieczarkami 425g','https://www.carrefour.pl/mrozonki/pizza-9s/dr-oetker-guseppe-pizza-z-szynka-i-pieczarkami-425-g'],
['maslo', 'Mlekovita Masło Polskie ekstra bez dodatków 82% 200g','https://www.carrefour.pl/mleko-nabial-jaja/maslo-margaryny-tluszcze/maslo/mlekovita-maslo-polskie-ekstra-bez-dodatkow-82-200-g'],
['jablka','Jabłka 1kg	','https://www.carrefour.pl/owoce-warzywa-ziola/owoce/owoce-swieze/jablka-szampion-wazone'],
['makaron','Lubella Penne Rigate Makaron Pióra 400g','https://www.carrefour.pl/artykuly-spozywcze/sypkie-i-produkty-zbozowe/makaron/lubella-pelne-ziarno-makaron-piora-400-g'],
['chleb','Chleb najtańszy bochen za 500g pszenny','https://www.carrefour.pl/piekarnia-ciastkarnia/chleb/chleb-danuty-450g-putka'],
['mydlo','Biały Jeleń Hipoalergiczne mydło naturalne premium z lnem 100 g','https://www.carrefour.pl/drogeria-kosmetyki-i-zdrowie/higienakosmetyki/mydlo-toaletowe/bialy-jelen-hipoalergiczne-mydlo-naturalne-100-g'],
['kurczak','Filet z piersi kurczaka','https://www.carrefour.pl/mieso/drob/kurczak/filet-z-piersi-kurczaka-tacka'],#'https://ezakupy.tesco.pl/groceries/pl-PL/search?query=filet%20z%20piersi%20kurczaka&sortBy=priceAscending'],
['jajka','jaja z wolnego wybiegu L 10 sztuk','https://www.carrefour.pl/mleko-nabial-jaja/jaja/top-jaj-jaja-wiejskie-z-wolnego-wybiegu-l-10-sztuk'],#'https://ezakupy.tesco.pl/groceries/pl-PL/search?query=jajka%20z%20wolnego%20wybiegu'],
['rolex','ROLEX Submariner Niebieski/18 karatowe białe złoto Ø40 mm	','https://www.czaszegarkow.pl/rolex-submariner-niebieski-18-karatowe-biale-zloto-o40-mm-p-7358.html'],
['whisky','Whisky Jack Daniels 0.5L	','https://outletalkoholowy.pl/bourbon/57-jack-daniels-05l.html'],
['piwo','Piwo Żywiec  czteropak puszka','https://sklep.spolemkielce.pl/produkt/piwo-zywiec-56-puszka-4x-500ml-zywiec/'],
['buty','Kazar damskie szpilki czułenka najtansze skórzane	','https://www.kazar.com/pl/sklep/kobieta/buty/czolenka/filtry/material,skora-cieleca/order,sortPriceUp/wysokosc-obcasa,wysoki-powyzej-8-cm'],
['auto','3 letnie używany golf srednia/mediana ze 100 ofert	','https://www.otomoto.pl/osobowe/volkswagen/golf/od-2018/?search%5Bfilter_enum_fuel_type%5D%5B0%5D=petrol&search%5Bfilter_enum_no_accident%5D=1&search%5Border%5D=filter_float_price%3Aasc&search%5Bbrand_program_id%5D%5B0%5D=&search%5Bcountry%5D='],
['telefon','Najlepszy flagowiec Samsunga','https://www.mediaexpert.pl/smartfony-i-zegarki/smartfony/smartfon-samsung-sm-s901-galaxy-s22-5g-8-128gb-black'],
['bigmac','BigMac','https://www.ubereats.com/pl/krakow/food-delivery/mcdonalds-galeria-krakowska-pietro/GsQ-ThCQQT6OQUCuTTFtJQ'],
['m2wtorny','Średnia cena m2 w Krakowie 50-60m2 wtórny	','https://www.morizon.pl/mieszkania/krakow/?ps%5Bliving_area_from%5D=50&ps%5Bliving_area_to%5D=60&ps%5Bmarket_type%5D%5B0%5D=2'],
['m2pierwotny','Średnia cena m2 w Krakowie 50-60m2 pierwotny','https://www.morizon.pl/mieszkania/rynek-pierwotny/krakow/?ps%5Bliving_area_from%5D=50&ps%5Bliving_area_to%5D=60'],
['benzyna','Benzyna 95 1L	','https://www.autocentrum.pl/stacje-paliw/auchan/auchan-henryka-kamienskiego-11-krakow/'],
['lot','Krakow-Rzym za 3 miesiace	','https://www.ryanair.com/ie/en/trip/flights/select?adults=1&teens=0&children=0&infants=0&dateOut=2022-02-01&dateIn=&isConnectedFlight=false&isReturn=false&discount=0&promoCode=&originIata=KRK&destinationIata=CIA&tpAdults=1&tpTeens=0&tpChildren=0&tpInfants=0&tpStartDate=2022-02-01&tpEndDate=&tpDiscount=0&tpPromoCode=&tpOriginIata=KRK&tpDestinationIata=CIA'],
#['Bilet to kina Cinecity w sobote wieczorem	'],
['fryzjer','Strzyżenie męskie Jean Luis David	','https://www.rezerwacje-jeanlouisdavid.pl/api/salon-prices/M58'],
['upc','Łącze internetowe najtanszne upc	','https://www.upc.pl/internet/kup-internet/'],
['prad','1Kwh w Tauron w dzień	','http://www.cena-pradu.pl/tauron.html'],
['lekarz','Cena wizyty konsultacja ortopedyczna srednia 10 ofert z znany lekarz	','https://www.znanylekarz.pl/szukaj?q=ortopeda&loc=Kraków%2C%20Polska&filters%5Bspecializations%5D%5B%5D=76&filters%5Bservices%5D%5B%5D=631&sorter=recommended'],
['aspiryna','Aspirin 500 mg 10 tabletek Bayer	','https://www.wapteka.pl/aspirin-500-mg-10-tabletek-2621,p'],
['karma','Karma Wiejska Zagroda Indyk z jagnięciną 9kg	','https://www.psiechrupki.pl/pl/p/Indyk-z-jagniecina-9kg-GRYZAKI-naturalne%2C-Wiejska-Zagroda/1001'],
['kasjer','Brutto Kasjera','https://www.jobted.pl/wynagrodzenie/kasjer'],
['xau','1 uncja Złota	','https://www.xe.com/currencyconverter/convert/?From=XAU&To=PLN'],
['chf','1 CHF	','https://www.xe.com/currencyconverter/convert/?Amount=1&From=chf&To=PLN'],
['usd','1 USD','https://www.xe.com/currencyconverter/convert/?Amount=1&From=usd&To=PLN'],
['kindle','Kindle Paperwhite 8gb bez reklam','https://www.ceneo.pl/72562365']
]
